name: Uffizzi CLI Rubygems Release
on:
  workflow_call:

jobs:
  gem-release:
    name: Build and publish image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release Ruby Gem
        run: make release_gem
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
