on:
  workflow_call:
    inputs:
      linux-bin-path:
        required: true
        type: string
      darwin-bin-path:
        required: true
        type: string
jobs:
  make-binary:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Install Linux dependencies'
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt update
          sudo apt install -y build-essential squashfs-tools curl gcc make bison
      - name: 'Install MacOs dependencies'
        if: matrix.os == 'macos-12'
        run: |
          brew install squashfs
      - uses: actions/checkout@v2
      - name: 'Set up Ruby'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.3'
      - name: 'Create Linux Bin'
        if: matrix.os == 'ubuntu-20.04'
        run: |
          wget https://github.com/pmq20/ruby-packer/releases/download/linux-x64/rubyc
          chmod +x ./rubyc
          ./rubyc --openssl-dir=/etc/ssl ./uffizzi --output=${{ inputs.linux-bin-path }}
      - name: 'Create Darwin Bin'
        if: matrix.os == 'macos-12'
        run: |
          export PATH="$(brew --prefix)/opt/openssl@1.1/bin:$PATH"
          export LDFLAGS="-L$(brew --prefix)/opt/openssl@1.1/lib"
          export CPPFLAGS="-I$(brew --prefix)/opt/openssl@1.1/include"
          export PKG_CONFIG_PATH="$(brew --prefix)/opt/openssl@1.1/lib/pkgconfig"
          export SSL_CERT_FILE=$(ruby -e "require 'openssl'; puts OpenSSL::X509::DEFAULT_CERT_FILE")

          wget https://github.com/pmq20/ruby-packer/releases/download/darwin-x64/rubyc
          chmod +x ./rubyc
          ./rubyc --openssl-dir=/etc/ssl ./uffizzi --output=${{ inputs.darwin-bin-path }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: matrix.os == 'ubuntu-20.04'
        with:
          name: ${{ inputs.linux-bin-path }}
          path: ${{ inputs.linux-bin-path }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: matrix.os == 'macos-12'
        with:
          name: ${{ inputs.darwin-bin-path }}
          path: ${{ inputs.darwin-bin-path }}
